// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:card_vault/data/cards/card_hive_model.dart';
import 'package:card_vault/data/groups/group_hive_model.dart';
import 'package:card_vault/data/settings/imported_font_hive_model.dart';
import 'package:card_vault/data/settings/settings_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(CardHiveModelAdapter());
    registerAdapter(GroupHiveModelAdapter());
    registerAdapter(ImportedFontHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(CardHiveModelAdapter());
    registerAdapter(GroupHiveModelAdapter());
    registerAdapter(ImportedFontHiveModelAdapter());
  }
}
